-- AlterTable
ALTER TABLE "Prova" ALTER COLUMN "pontosCumprir" SET DEFAULT 0,
ALTER COLUMN "pontosCumprir" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "RegraColocacao" ALTER COLUMN "pontos" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Resultado" ALTER COLUMN "pontos" SET DATA TYPE DOUBLE PRECISION;
